server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:9000/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-provider-user