server:
  port: 80
  #上下文路径
  servlet:
    context-path: /boot
#日志配置
logging:
  file: logs/demo.log
  level.*: debug
#thymeleaf 配置
spring:
  thymeleaf:
    cache: false #关闭缓存
    mode: LEGACYHTML5 #去掉html语法校验
  #指定profile
  profiles:
    active: company
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yangtao.demo.model


