server:
  port: 8080
spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:9000/eureka/
  instance:
    prefer-ip-address: true

#自定义鉴权配置
auth:
  isEnabled: true
  expireDate: 1

